-- Music Store Database Schema
-- H2 Database

CREATE TABLE IF NOT EXISTS PRODUTO (
  ID           BIGINT        NOT NULL AUTO_INCREMENT,
  CODIGOID     VARCHAR(6)    NOT NULL,
  MODELO       VARCHAR(100)  NOT NULL,
  ESTILO       VARCHAR(100)  NULL,
  DESCRICAO    VARCHAR(1000) NULL,
  PRECO_COMPRA DECIMAL(9,2)  NOT NULL,
  ESPECIFICACOES VARCHAR(1000) NULL,
  PRECO_VENDA  DECIMAL(9,2)  NOT NULL,
  QUANTIDADE   INT           NOT NULL DEFAULT 0,
  DISPONIVEL   BOOLEAN       NOT NULL DEFAULT TRUE,
  DT_CADASTRO  TIMESTAMP     NOT NULL,
  CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CATEGORIA (
  ID   INT    NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID),
  CONSTRAINT UC_NOME UNIQUE (NOME)
);

CREATE TABLE IF NOT EXISTS SUBCATEGORIA (
  ID   INT  NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  CONSTRAINT PK_SUB_CATEGORIA PRIMARY KEY (ID),
  CONSTRAINT UC_SUB_NOME UNIQUE (NOME)
);

CREATE TABLE IF NOT EXISTS USUARIO (
  ID           BIGINT        NOT NULL AUTO_INCREMENT,
  NOME         VARCHAR(100)  NOT NULL,
  CPF          BIGINT        NOT NULL,
  NASCIMENTO   BIGINT        NOT NULL,
  TELEFONE     BIGINT        NOT NULL,
  CEP          VARCHAR(10)   NOT NULL,
  RUA          VARCHAR(100)  NOT NULL,
  NUMERO       INT           NOT NULL DEFAULT 0,
  COMPLEMENTO  VARCHAR(20)   NULL,
  BAIRRO       VARCHAR(100)  NOT NULL,
  CIDADE       VARCHAR(50)   NOT NULL,
  ESTADO       VARCHAR(2)    NOT NULL,
  EMAIL        VARCHAR(100)  NOT NULL,
  SENHA        VARCHAR(100)  NOT NULL,
  CONSTRAINT PK_USUARIO PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CARRINHO (
  ID            BIGINT       NOT NULL AUTO_INCREMENT,
  TOTAL_ITEM    INT          NULL,
  VALOR_TOTAL   INT          NOT NULL DEFAULT 0,
  FRETE         INT          NOT NULL DEFAULT 30,
  VALOR_COMPRA  INT          NOT NULL,
  CONSTRAINT PK_CARRINHO PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS VENDA (
  ID            BIGINT       NOT NULL AUTO_INCREMENT,
  USUARIO       VARCHAR(100) NOT NULL,
  TOTAL_ITEM    INT          NULL,
  VALOR_TOTAL   INT          NOT NULL DEFAULT 0,
  FRETE         INT          NOT NULL DEFAULT 30,
  VALOR_COMPRA  INT          NOT NULL,
  DATA          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_VENDA PRIMARY KEY (ID)
);

